# Core PT-BR user-facing presentation string labels (Localization/Strings Separation Pattern)
# Separating visual UI labels from technical database schema constants (Clean Architecture)

# 1. Detailed Holdings Grid Headers
DISPLAY_CODE = "Código"
DISPLAY_NAME = "Nome"
DISPLAY_QTY = "Quantidade"
DISPLAY_AVG_PRICE = "Preço médio"
DISPLAY_ADJ_PRICE = "Preço Ajustado"
DISPLAY_INVESTED = "Investido"
DISPLAY_CURRENT = "Atual"
DISPLAY_QUOTE_TODAY = "Cotação hoje"
DISPLAY_RETURN_PCT = "Rendimento %"
DISPLAY_RESULT = "Resultado"
DISPLAY_YOC = "YoC"
DISPLAY_YOC_12 = "YoC/12"
DISPLAY_EARNINGS = "Proventos"
DISPLAY_SECTOR = "Setor"

# 2. Market Monitor Grid Headers
DISPLAY_TICKER = "Ticker"
DISPLAY_COMPANY = "Empresa"
DISPLAY_QUOTE = "Cotação"
DISPLAY_CEILING = "Preço Teto"
DISPLAY_AVG_5Y = "Média 5a"
DISPLAY_DY_AVG_5Y = "DY Médio 5a"
DISPLAY_P_VP = "P/VP"
DISPLAY_P_L = "P/L"
DISPLAY_DY_CURRENT = "DY Atual"
DISPLAY_ROE = "ROE"
DISPLAY_RANGE_52W = "Faixa 52s"

# 3. Price-Ceiling model selection option string values (Presentation Strings)
MODEL_CLASSIC = "Bazin Clássico"
MODEL_SELIC = "SELIC Nominal"
MODEL_IPCA_SPREAD = "IPCA + Spread Alvo"

# 4. View UI Labels and Messages
MSG_PORTFOLIO_EMPTY = "Sua carteira está vazia. Vá até a aba 'Ativos' para inserir seus ativos ou importar seu extrato da B3!"
MSG_MARKET_MONITOR_TITLE = "📈 Central de Monitoramento de Mercado (Bazin)"
MSG_MARKET_MONITOR_DESC = "Acompanhe empresas da B3 em tempo real e identifique oportunidades de compra utilizando o modelo de Preço Teto de Décio Bazin."
MSG_INVALID_ASSET_SELECTION = "Por favor, selecione um ativo válido da lista."
MSG_NO_ASSETS_MONITOR = "Nenhuma empresa adicionada ao monitor. Digite um ticker no formulário acima para começar a acompanhar!"
MSG_MONITORED_ASSETS_PANEL = "Painel de Ativos Monitorados"
MSG_YF_FETCH_ERROR = "Falha ao obter dados do Yahoo Finance para as empresas monitoradas. Verifique se digitou os tickers corretamente."
MSG_ADJUST_DIVIDENDS_EXPANDER = "🔧 Ajustar Proventos Históricos (Bazin)"
MSG_ADJUST_DIVIDENDS_DESC = "Caso identifique erros de omissão de dividendos no Yahoo Finance (como JCPs complementares), corrija os valores consolidados de cada ano abaixo:"
MSG_INVALID_ASSET_CORRECTION = "Por favor, selecione um ativo válido para aplicar a correção."
MSG_DIVIDEND_CORRECTION_ERROR = "Erro ao salvar a correção de dividendos."

MSG_MANUAL_ENTRY_TITLE = "Registrar Lançamento Manual"
MSG_SMART_IMPORTER_TITLE = "🚀 Importador Inteligente da B3"
MSG_SMART_IMPORTER_DESC = "Exporte o arquivo Excel (.xlsx) da sua Área do Investidor B3 (Movimentação) e arraste-o aqui para importar todas as transações e dividendos de uma única vez."

MSG_PLANNING_DESC = "Calcule as metas de patrimônio necessárias e simule a sua curva de independência financeira utilizando as taxas reais da carteira."
MSG_PLANNING_LOAD_ERROR = "Falha ao carregar as configurações do planejador."
MSG_PLANNING_INVESTED_CAPITAL = "Capital Investido Atual"
MSG_PLANNING_LIFE_PARAMS = "Seus Parâmetros de Vida"
MSG_UPDATE_MW_BTN = "🔄"
MSG_BCB_FETCH_ERROR = "Falha ao recuperar dados oficiais do BCB."

MSG_PORTFOLIO_DETAIL_TITLE = "📁 Detalhamento de Ativos em Carteira"
MSG_PORTFOLIO_EMPTY_ASSETS = "Nenhum ativo em custódia encontrado. Vá na aba 'Ativos' para inserir seus ativos!"
MSG_DIVIDENDS_DYNAMIC_TABLE = "📅 Tabela Dinâmica de Proventos do Ativo"
MSG_VIEW_DETAILED_YEAR_TABLE = "🔍 Ver Tabela Resumo Detalhada do Ano"
MSG_ASSET_GENERAL_INDICATORS = "#### 📊 Indicadores Gerais do Ativo"
MSG_CHART_BEHAVIOR = "##### 📈 Comportamento Gráfico"
MSG_NO_YF_CHART_DATA = "Dados gráficos de cotações não disponíveis para este ativo no Yahoo Finance."
MSG_TX_EXTRACT_TITLE = "#### 📂 Extrato de Transações e Proventos"
MSG_DETAILED_CONTRIBUTIONS = "🛒 Aportes Detalhados"
MSG_NO_TX_RECORDED = "Nenhuma transação registrada."
MSG_RECEIVED_DIVIDENDS = "💰 Proventos Recebidos"
MSG_NO_DIVIDENDS_RECORDED_SIMPLE = "Nenhum provento registrado."

MSG_HISTORIC_EVOLUTION_TITLE = "📈 Evolução Patrimonial Histórica & Planejamento"
MSG_HISTORIC_CONTRIBUTIONS_TITLE = "📊 Histórico de Aportes por Ano e Mês"

MSG_CUSTODY_ASSETS_TITLE = "Ativos em Custódia (Detalhado)"

MSG_LONG_TERM_PROJECTION_TITLE = "📈 Projeção Acumulada de Longo Prazo"
MSG_CONSTANT_CONTRIB_VS_INTEREST_TITLE = "📊 Aporte Constante vs. Juros Crescente"

MSG_SIMULATION_RESULTS_TITLE = "🎯 Resultados da Simulação"
MSG_INVESTMENT_TIMEFRAMES_TITLE = "⏳ Prazos de Investimentos"

# Help Tooltips
HELP_MARKET_MONITOR_SEARCH = "Digite para buscar e autocompletar ativos válidos por ticker ou nome da empresa cadastrados no assets.csv"
HELP_OPS_SEARCH = "Digite para buscar pelo ticker ou por qualquer parte do nome da empresa cadastrada no assets.csv"
HELP_PLANNING_AUTOMATED = "Calculado de forma automatizada a partir do seu histórico de compras na B3"
HELP_UPDATE_MW = "Atualizar valor do salário mínimo da nuvem (API SGS Banco Central)"
HELP_QTY_END_YEAR = "Quantidade total de cotas na sua posse até o último dia do ano selecionado"
HELP_TOTAL_PAID_PER_SHARE = "Soma de todos os proventos unitários recebidos por cota neste ano selecionado"
HELP_ADJ_PRICE = "Preço Médio descontado dos dividendos recebidos. Mostra o seu real custo de aquisição (Basis)."
HELP_AVG_PRICE = "Preço Médio ponderado de todas as compras (não impactado por proventos)."
HELP_YOC = "Yield on Cost: Retorno em dividendos totais sobre o capital inicialmente investido."
HELP_YOC_12 = "Yield on Cost de 12 meses: Retorno em dividendos nos últimos 12 meses sobre o capital investido."
HELP_RETURN_PCT = "Retorno Percentual: Lucro/Prejuízo em relação ao valor investido."
HELP_RESULT = "Lucro/Prejuízo financeiro total da posição."
HELP_EARNINGS = "Soma de todos os proventos recebidos por este ativo."
HELP_WEIGHT_PCT = "Peso atual do ativo no patrimônio total da carteira."
HELP_CEILING = "Preço Teto calculado com base na média de dividendos dos últimos 5 anos e no Dividend Yield alvo."

DISPLAY_WEIGHT = "Peso %"

# Metric Labels and Helpers (Patrimony and Portfolio)
LABEL_PATRIMONY_TOTAL = "Patrimônio Atual"
LABEL_CAPITAL_INVESTED = "Capital Investido"
LABEL_DIVIDENDS_TOTAL = "Proventos Totais"
LABEL_DIVIDENDS_L12M = "Proventos 12 Meses (L12M)"
LABEL_DIVIDENDS_YTD = "Proventos Ano Corrente (YTD)"
LABEL_DIVIDENDS = "Dividendos"
LABEL_JCP = "JCP"
LABEL_YIELDS = "Rendimentos"
LABEL_TOTAL_RECEIVED = "Total Recebido"
LABEL_QUANTITY = "Quantidade"
LABEL_TOTAL_PER_SHARE = "Total por Ação"
LABEL_ADJ_PRICE_CURRENT = "Preço Ajustado (Atual)"
LABEL_AVG_PRICE = "Preço Médio (PM)"
LABEL_DY = "Dividend Yield (DY)"
LABEL_YOC_12_MONTHLY = "YoC / 12"
LABEL_PE_RATIO = "Índice P/L"
LABEL_P_VP = "P/VP"
LABEL_HIGH_52W = "Alt. 52 Semanas"
LABEL_LOW_52W = "Bai. 52 Semanas"

HELP_DY = "O Dividend Yield é uma métrica que compara o dividendo pago por uma ação com o preço da ação. É calculado dividindo o dividendo por ação pelo preço da ação."
HELP_PE_RATIO = "O P/L compara o preço de uma ação com o lucro por ação. Indica o quão dispostos os investidores estão a pagar por cada real de lucro."
HELP_P_VP = "O P/VP compara o preço de uma ação com o valor patrimonial da empresa. Indica se a ação está descontada (abaixo de 1) ou sobrevalorizada em relação ao seu patrimônio."
HELP_QTY_NO_CHANGE = "Nenhuma alteração na quantidade de cotas em relação ao ano de {prev_year} (posição estável em {qty_prev_year} cotas)."
HELP_PATRIMONY_RETURN = "Retorno: {val:+.2f}%"
HELP_YOC_TOTAL = "YoC Total: {val:.2f}%"
HELP_YOC_L12M = "YoC L12M: {val:.2f}%"
HELP_PLANNING_PARAM = "Parâmetro do Planejamento"

MSG_ASSET_ADDED_SUCCESS = "Ativo {ticker} adicionado com sucesso ao monitor!"
MSG_ASSET_ADD_ERROR = "Erro ao adicionar o ativo {ticker} (ou ele já existe no monitor)."
MSG_CONFIRM_REMOVE = "🗑️ Confirmar Remoção de {ticker}"
MSG_ASSET_REMOVED_SUCCESS = "Ativo {ticker} removido com sucesso!"
MSG_DIVIDEND_CORRECTION_SUCCESS = "Proventos de {ticker} para o ano de {year} corrigidos com sucesso para {value}!"
MSG_MANUAL_ENTRY_SUCCESS_TX = "Sucesso! {tx_type} de {qty}x {ticker} salva no banco de dados!"
MSG_MANUAL_ENTRY_SUCCESS_DIV = "Sucesso! Recebimento de R$ {value} em {div_type} de {ticker} registrado!"
MSG_SMART_IMPORTER_SUCCESS = "Importação realizada com sucesso! Foram adicionadas {tx_count} novas transações e {div_count} registros de proventos no banco de dados local!"
MSG_SMART_IMPORTER_ERROR = "Erro ao processar arquivo B3. Certifique-se de que é o arquivo oficial da Área do Investidor. Detalhes: {e}"
MSG_BCB_CONN_ERROR = "Erro ao conectar com a API do BCB: {e}"
MSG_ASSET_INFO_CNPJ = "**CNPJ:** {cnpj}  \n**Setor:** {sector}  \n**Segmento:** {segment}"
MSG_NO_DIVIDENDS_RECORDED = "Nenhum provento recebido registrado para o ativo {ticker} no banco de dados."
MSG_ANNUAL_PLANNING_TITLE = "📅 Planejamento Anual de Investimentos ({year})"
MSG_YTD_CONTRIBUTIONS = "**Total Comprado (Aportado) este ano na B3:** {value} ({pct:.1f}%)"
MSG_REMAINING_TO_BUY = "🔴 **Falta comprar/reinvestir na B3 para bater a meta:** {value}"
MSG_ALL_GOALS_MET = "🎉 **Excelente! Todos os aportes mínimos e proventos do ano foram totalmente investidos e reinvestidos na B3!**"
MSG_REAL_VS_PLANNED_TITLE = "📊 Histórico Real vs. Planejado (Com Projeção de {months} Meses no Futuro)"
MSG_REAL_VS_PLANNED_DESC = "Compare as curvas planejadas no seu cockpit contra os dados reais colhidos da B3. A linha pontilhada extrapola a tendência do seu ritmo real pelos próximos {months} meses!"
HELP_INCOME_MULTIPLIER = "Multiplicador: Define a renda com base em salários mínimos. O salário mínimo atual cadastrado é {value}."
LABEL_CURRENT_PRICE = "Cotação Atual"
HELP_CURRENT_PRICE = "Cotação em tempo real consultada via Yahoo Finance (B3)."
